

spring:
  cloud:
    gateway:
      default-filters:
        - name : GlobalDefaultFilter
          args:
            pre-logger: true
            post-logger: true
      routes:
        - id: thumbnail
          uri: ${THUMBNAIL_URI:http://localhost}:${THUMBNAIL_APP_PORT:8095}
          predicates:
            - Path=/thumbnail/**
          filters:
            - name: ThumbnailFilter
              args:
                message : execute message
            - RewritePath=/thumbnail/(?<path>.*),/$\{path}
  application:
    name: gateway


server:
  port: ${GATEWAY_APP_PORT:9000}

logging:
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost}:9411/api/v2/spans
