

spring:
  cloud:
    gateway:
      default-filters:
        - name : GlobalDefaultFilter
          args:
            pre-logger: true
            post-logger: true
      routes:
        - id: thumbnail
          uri: ${THUMBNAIL_URI:http://localhost}:${THUMBNAIL_APP_PORT:8090}
          predicates:
            - Path=/thumbnail/**
          filters:
            - name: ThumbnailFilter
              args:
                message : execute message
            - RewritePath=/thumbnail/(?<path>.*),/$\{path}

server:
  port: ${GATEWAY_APP_PORT:9000}

logging:
  level:
    web: debug
