spring:
  data:
    mongodb:
      username: ${MONGO_BASE_USER:tis}
      password: ${MONGO_BASE_PASSWORD:tis}
      authentication-database: admin
      host: ${MONGO_BASE_HOST:localhost}
      port: ${MONGO_BASE_PORT:27017}
server:
  port: ${THUMBNAIL_APP_PORT:8095}

logging:
  level:
    root: info
